[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "xilophor"
name = "LethalNetworkAPI"
description = "A library/API to allow developers to easily add networking to their mods."
websiteUrl = "https://github.com/Xilophor/LethalNetworkAPI"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Lordfirespeed-OdinSerializer = "2022.11.9"
BMX-LobbyCompatibility = "1.1.0"

[build]
icon = "icon.png"
readme = "../README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../LethalNetworkAPI/bin/Release/netstandard2.1/LethalNetworkAPI.dll"
target = "/BepInEx/plugins/LethalNetworkAPI/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "bepinex", "libraries", "serverside", "clientside" ]
