name: Build

on:
  push:
    branches: [main]
  pull_request: 

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Restore Solution
        run: |
          dotnet restore
          dotnet tool restore

      - name: Pack Solution
        run: |
          dotnet pack --configuration Release

      - name: Build Debug
        run: |
          dotnet build --configuration Debug

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: dist/*.zip

      - name: Upload NuPkg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: LethalNetworkAPI/bin/Release/*.nupkg

      - name: Upload Debug Dll
        uses: actions/upload-artifact@v4
        with:
          name: debug-build
          path: LethalNetworkAPI/bin/Debug/netstandard2.1/LethalNetworkAPI.dll